version: '3'
services:
    apache:
        build: .docker/apache
        container_name: sf5_apache
        ports:
          - 80:80
        volumes:
          - .docker/config/vhosts:/etc/apache2/sites-enabled
          - .:/home/wwwroot/sf5
        depends_on:
          - php

    mysql:
        image: mysql
        command: "--default-authentication-plugin=mysql_native_password"
        container_name: sf5_mysql
        volumes:
            - .docker/data/db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: pass
            MYSQL_DATABASE: projet-symfony
            MYSQL_USER: user
            MYSQL_PASSWORD: pass

    php:
        build: .docker/php
        container_name: sf5_php
        volumes:
          - .:/home/wwwroot/sf5
        depends_on:
          - mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: sf5_phpmyadmin
        environment:
          PMA_HOST: mysql
          PMA_PORT: 3306
        ports:
            - 8080:80
        links:
            - mysql